<?php

declare(strict_types=1);

use Illuminate\Filesystem\Filesystem;
use Illuminate\Foundation\Application;
use Illuminate\Routing\Router;
use Veltix\WayfinderLocales\Tests\Concerns\WritesLangFiles;

use function Orchestra\Testbench\Pest\defineEnvironment;
use function Orchestra\Testbench\Pest\defineRoutes;
use function Orchestra\Testbench\Pest\setUp;
use function Orchestra\Testbench\Pest\tearDown;

uses(WritesLangFiles::class);

setUp(function ($parent): void {
    $this->setUpWorkspace([
        'en/messages.php' => ['greeting' => 'Hello :name', 'nested' => ['deep' => 'Deep']],
        'de/messages.php' => ['greeting' => 'Hallo :name', 'nested' => ['deep' => 'Tief']],
        'en/routes.php' => ['search' => 'search'],
        'de/routes.php' => ['search' => 'suche'],
    ]);

    $parent();
});

tearDown(function (): void {
    $this->tearDownWorkspace();
});

defineEnvironment(function (Application $app): void {
    $app->useLangPath($this->workspace.'/lang');
    $app['config']->set('wayfinder-locales.locales', ['en', 'de']);
    $app['config']->set('wayfinder-locales.default_locale', 'en');
});

defineRoutes(function (Router $router): void {
    $router->get('/greet', fn () => 'hi')->name('greet');
});

it('emits both catalogs for a two locale app', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    $this->assertFileExists($this->output.'/translations/en.ts');
    $this->assertFileExists($this->output.'/translations/de.ts');

    expect($this->generated('translations/en.ts'))->toContain('Hello :name');
    expect($this->generated('translations/de.ts'))->toContain('Hallo :name');

    $index = $this->generated('translations/index.ts');
    expect($index)->toContain("'en': () => import('./en')");
    expect($index)->toContain("'de': () => import('./de')");

    expect($this->generated('translations/locales.ts'))
        ->toContain("export type Locale = 'en' | 'de';");
});

it('flattens lang group files into dotted catalog keys', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    $en = $this->generated('translations/en.ts');

    expect($en)->toContain('"messages.greeting"');
    expect($en)->toContain('"messages.nested.deep"');

    $keys = $this->generated('translations/keys.ts');

    expect($keys)->toContain("'messages.greeting'");
    expect($keys)->toContain("'messages.nested.deep'");
});

it('types the placeholders of each key', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    expect($this->generated('translations/keys.ts'))
        ->toContain("'messages.greeting': { name: string | number };");
});

it('excludes the configured lang groups', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    expect($this->generated('translations/en.ts'))->not->toContain('routes.search');
    expect($this->generated('translations/en.ts'))->toContain('messages.greeting');
});

it('does not generate actions or routes', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    $this->assertDirectoryDoesNotExist($this->output.'/actions');
    $this->assertDirectoryDoesNotExist($this->output.'/routes');
});

it('writes nothing into wayfinders own output directory', function (): void {
    $files = new Filesystem;
    $files->ensureDirectoryExists($this->output.'/wayfinder');
    $files->put($this->output.'/wayfinder/index.ts', '// generated by laravel/wayfinder');

    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    expect(array_map(fn ($file) => $file->getFilename(), $files->files($this->output.'/wayfinder')))
        ->toBe(['index.ts']);
    expect($files->get($this->output.'/wayfinder/index.ts'))->toBe('// generated by laravel/wayfinder');
});

it('generates a self contained runtime', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    $locales = $this->generated('translations/locales.ts');

    expect($locales)->toContain('export const setLocale');
    expect($locales)->toContain('export const getLocale');
    expect($locales)->toContain("export const locales: Locale[] = ['en', 'de'];");

    $runtime = $this->generated('translations/index.ts');

    expect($runtime)->toContain('import { defaultLocale, getLocale, type Locale } from "./locales";');
    expect($runtime)->not->toContain('../wayfinder');
});

it('prunes catalogs for locales that are no longer configured', function (): void {
    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    $this->assertFileExists($this->output.'/translations/de.ts');

    config()->set('wayfinder-locales.locales', ['en']);

    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->assertSuccessful();

    $this->assertFileDoesNotExist($this->output.'/translations/de.ts');
    $this->assertFileExists($this->output.'/translations/en.ts');
});

it('fails when no locales are configured', function (): void {
    config()->set('wayfinder-locales.locales', []);

    $this->artisan('wayfinder-locales:generate', ['--path' => $this->output])
        ->expectsOutputToContain('No locales configured')
        ->assertFailed();
});
