<?php

declare(strict_types=1);

namespace Veltix\WayfinderLocales;

use Illuminate\Config\Repository;
use Illuminate\Routing\Route as IlluminateRoute;
use Illuminate\Routing\Router;
use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;
use Laravel\Ranger\Components\Route as RangerRoute;
use Laravel\Wayfinder\Converters\FormRequests;
use Laravel\Wayfinder\Converters\InertiaData;
use Laravel\Wayfinder\Converters\JsonApiData;
use Laravel\Wayfinder\Converters\JsonData;
use Laravel\Wayfinder\Converters\ResourceData;
use Laravel\Wayfinder\Converters\Routes as WayfinderRoutes;
use Veltix\WayfinderLocales\Middleware\SetLocale;
use Veltix\WayfinderLocales\Route\LocaleRouteResolver;
use Veltix\WayfinderLocales\Wayfinder\LocaleAwareRouteTransformer;
use Veltix\WayfinderLocales\Wayfinder\TypeScriptEmitterExtension;

/**
 * Wires the package into `laravel/wayfinder` on the `next` branch.
 *
 * Routes are generated by Wayfinder itself: the `Routes` converter binding is
 * swapped for one that recognises `Route::localized([...])` metadata and emits
 * a per-locale URL template table. Translation catalogs are generated by this
 * package's own command, which has nothing to do with routing.
 */
class WayfinderLocalesServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergeConfigFrom(__DIR__.'/../config/wayfinder-locales.php', 'wayfinder-locales');

        $this->app->singleton(LocaleRouteResolver::class, fn ($app): LocaleRouteResolver => new LocaleRouteResolver(
            router: $app->make(Router::class),
            config: $app->make(Repository::class),
        ));

        $this->app->singleton(TypeScriptEmitterExtension::class, fn ($app): TypeScriptEmitterExtension => new TypeScriptEmitterExtension(
            config: $app->make(Repository::class),
        ));

        $this->app->bind(WayfinderRoutes::class, fn ($app): WayfinderRoutes => new LocaleAwareRouteTransformer(
            inertiaDataConverter: $app->make(InertiaData::class),
            jsonDataConverter: $app->make(JsonData::class),
            resourceDataConverter: $app->make(ResourceData::class),
            jsonApiDataConverter: $app->make(JsonApiData::class),
            formRequestConverter: $app->make(FormRequests::class),
            config: $app->make(Repository::class),
            localeRouteResolver: $app->make(LocaleRouteResolver::class),
            emitterExtension: $app->make(TypeScriptEmitterExtension::class),
        ));
    }

    public function boot(): void
    {
        $this->registerLocalizedRouteMacro();

        $this->app['router']->aliasMiddleware('setlocale', SetLocale::class);

        if (! $this->app->runningInConsole()) {
            return;
        }

        $this->commands([
            GenerateLocalizedCommand::class,
        ]);

        $this->publishes([
            __DIR__.'/../config/wayfinder-locales.php' => config_path('wayfinder-locales.php'),
        ], 'wayfinder-locales-config');
    }

    /**
     * `Route::localized(['en' => 'products', 'de' => 'produkte'])` tags a route
     * with its per-locale path segments. The tag is read back at generation
     * time by {@see LocaleRouteResolver}, which is also reused here: for every
     * locale whose resolved URI still carries the `{locale}`/`{locale?}`
     * placeholder, a concrete twin route is registered — `/de/produkte` next to
     * the original `/{locale}/produkte` — named `{name}.locale.{locale}`, with
     * `locale` set as a route default so `SetLocale` picks it up unchanged and
     * inbound requests match natively (`route:cache` included). The original
     * `{locale}`-parameterised route is left registered: {@see
     * LocaleRouteResolver} reads its `uri()` to detect the placeholder, and it
     * is what `route('products')` keeps resolving through for callers that
     * don't care about locale.
     */
    private function registerLocalizedRouteMacro(): void
    {
        if (IlluminateRoute::hasMacro('localized')) {
            return;
        }

        IlluminateRoute::macro('localized', function (array $translations): IlluminateRoute {
            /** @var IlluminateRoute $this */
            $action = $this->getAction();
            $actionKey = (string) config('wayfinder-locales.action_key', 'wayfinder_locales');
            $action[$actionKey] = [
                'translations' => $translations,
            ];

            $this->setAction($action);

            $hideDefault = (bool) config('wayfinder-locales.hide_default_prefix', false);
            $defaultLocale = config('wayfinder-locales.default_locale');
            $localeParameter = (string) config('wayfinder-locales.locale_parameter', 'locale');

            if ($hideDefault && is_string($defaultLocale) && $defaultLocale !== '') {
                $uri = $this->uri();
                $requiredPlaceholder = '{'.$localeParameter.'}';
                $optionalPlaceholder = '{'.$localeParameter.'?}';

                $segments = explode('/', trim($uri, '/'));
                $stripped = array_values(array_filter(
                    $segments,
                    static fn (string $s): bool => $s !== $requiredPlaceholder && $s !== $optionalPlaceholder,
                ));

                $unprefixedUri = implode('/', $stripped);

                /** @var Router $router */
                $router = app(Router::class);

                $methods = $this->methods();
                $routeAction = $this->getAction();

                unset($routeAction['as']);

                $defaultRoute = $router->addRoute($methods, $unprefixedUri, $routeAction);
                $defaultRoute->defaults($localeParameter, $defaultLocale);

                if ($this->getName() !== null) {
                    $defaultRoute->name($this->getName().'.default');
                }

                foreach ($this->excludedMiddleware() as $middleware) {
                    $defaultRoute->withoutMiddleware($middleware);
                }
            }

            /** @var Router $router */
            $router = app(Router::class);

            // `LocaleRouteResolver` looks routes up by name first. That lookup
            // table is normally refreshed once, lazily, when the app finishes
            // booting — but this macro runs while routes are still being
            // registered, before that happens, so `$this`'s own name (already
            // set by the time `.localized()` is chained on) would not resolve
            // yet without forcing the refresh here.
            $router->getRoutes()->refreshNameLookups();

            /** @var LocaleRouteResolver $resolver */
            $resolver = app(LocaleRouteResolver::class);

            $metadata = $resolver->resolveForRangerRoute(new RangerRoute($this, new Collection, null, null));

            if ($metadata !== null) {
                $requiredPlaceholder = '{'.$localeParameter.'}';
                $optionalPlaceholder = '{'.$localeParameter.'?}';
                $methods = $this->methods();

                foreach ($metadata->locales as $locale) {
                    $template = $metadata->uriForLocale($locale);

                    if ($template === null) {
                        continue;
                    }

                    if (! str_contains($template, $requiredPlaceholder) && ! str_contains($template, $optionalPlaceholder)) {
                        // No placeholder left to fill means this is the unprefixed
                        // default-locale URI already registered above.
                        continue;
                    }

                    $concreteUri = str_replace([$optionalPlaceholder, $requiredPlaceholder], $locale, $template);

                    $routeAction = $this->getAction();
                    unset($routeAction['as']);

                    $localeRoute = $router->addRoute($methods, $concreteUri, $routeAction);
                    $localeRoute->defaults($localeParameter, $locale);

                    if ($this->getName() !== null) {
                        $localeRoute->name($this->getName().'.locale.'.$locale);
                    }

                    foreach ($this->excludedMiddleware() as $middleware) {
                        $localeRoute->withoutMiddleware($middleware);
                    }
                }
            }

            return $this;
        });
    }
}
